# Generated by Django 4.1.5 on 2024-08-26 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tms', '0001_initial'),
        ('knowledge_management_system', '0001_initial'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kmsprospect',
            name='prospect',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kms', to='tms.target'),
        ),
        migrations.AddField(
            model_name='kmsproject',
            name='project',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='kms', to='project.project'),
        ),
        migrations.AddField(
            model_name='kmshistoricalreport',
            name='kms_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knowledge_management_system.kmsproject'),
        ),
        migrations.AddField(
            model_name='kmshistoricalreport',
            name='prospect_tags',
            field=models.ManyToManyField(to='knowledge_management_system.kmsprospect'),
        ),
        migrations.AddConstraint(
            model_name='company',
            constraint=models.UniqueConstraint(condition=models.Q(('acn__isnull', False)), fields=('acn',), name='unique_acn_not_null'),
        ),
        migrations.AddConstraint(
            model_name='company',
            constraint=models.UniqueConstraint(condition=models.Q(('abn__isnull', False)), fields=('abn',), name='unique_abn_not_null'),
        ),
    ]
