# Generated by Django 4.1.5 on 2024-08-26 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0002_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('media_file', '0001_initial'),
        ('lms', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectparcel',
            name='user_updated',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='parcelownerrelationship',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcel_relationships', to='lms.parcelowner'),
        ),
        migrations.AddField(
            model_name='parcelownerrelationship',
            name='parcel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_relationships', to='lms.projectparcel'),
        ),
        migrations.AddField(
            model_name='parcelownerrelationship',
            name='user_created',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_land_parcel_relationships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='parcelownerrelationship',
            name='user_updated',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_land_parcel_relationships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='parcelowner',
            name='files',
            field=models.ManyToManyField(blank=True, related_name='land_parcel_owner_files', to='media_file.mediafile'),
        ),
        migrations.AddField(
            model_name='parcelowner',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project'),
        ),
        migrations.AddField(
            model_name='parcelowner',
            name='user_created',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_land_parcel_owners', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='parcelowner',
            name='user_updated',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_land_parcel_owners', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lmshistory',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='lmshistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='landparcelownertask',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='lms.parcelowner'),
        ),
        migrations.AddField(
            model_name='landparcelownertask',
            name='user_created',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_created_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='landparcelownertask',
            name='user_updated',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='landparcelownerreminder',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='lms.parcelowner'),
        ),
        migrations.AddField(
            model_name='landparcelownerreminder',
            name='user_created',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_created_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='landparcelownerreminder',
            name='user_updated',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='landparcelownernote',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='lms.parcelowner'),
        ),
        migrations.AddField(
            model_name='landparcelownernote',
            name='user_created',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_created_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='landparcelownernote',
            name='user_updated',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='landparcelownercorrespondence',
            name='files',
            field=models.ManyToManyField(blank=True, related_name='land_parcel_owner_correspondence_files', to='media_file.mediafile'),
        ),
        migrations.AddField(
            model_name='landparcelownercorrespondence',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correspondence', to='lms.parcelowner'),
        ),
        migrations.AddField(
            model_name='landparcelownercorrespondence',
            name='user_created',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_created_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='landparcelownercorrespondence',
            name='user_updated',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='projectparcel',
            unique_together={('project', 'parcel')},
        ),
        migrations.AddConstraint(
            model_name='parcelownerrelationship',
            constraint=models.UniqueConstraint(fields=('parcel', 'owner'), name='unique_parcel_owner', violation_error_message='The Owner already exists within this Parcel.'),
        ),
        migrations.AlterUniqueTogether(
            name='parcelowner',
            unique_together={('project', 'title', 'first_name', 'last_name', 'date_birth', 'gender')},
        ),
    ]
